spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dndcharactersheet_db
    username: root
    password: 170984St
    driver-class-name: com.mysql.cj.jdbc.Driver

jpa:
  hibernate:
    ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

#  # (Optional) Enable this if you want detailed SQL logs for debugging
#  logging:
#    level:
#      org.hibernate.SQL: DEBUG
#      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#      org.hibernate: DEBUG
#        org.springframework: DEBUG